#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Write your code here
    valleys =0
    total  = 0
    for i in range(steps):
       
        if path[i] == "U":
            total += 1
        elif path[i] =="D":
            total -= 1
        if i + 1 < steps and path[i+1] == "U" and total + 1==0:
            print("a")
            valleys += 1
        print("i: ",i, "total: ", total)
    return valleys

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
