#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    i = n-1
    m = 0
    while i>0:
        if arr[i] < arr[i-1]:
            m = arr[i]
            arr[i]=arr[i-1]
            print(*arr, sep=" ")
            arr[i-1] = m
        i -= 1
    print(*arr, sep=" ")
            
    return
                

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
